{{- $deployment := .Values.backend -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}-eventbus
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}-eventbus
  annotations: 
    released: {{ .Release.Time}}    
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $deployment.role }}-eventbus
  replicas: {{ $deployment.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $deployment.role }}-eventbus
    spec:
      containers:
      - name: {{ $deployment.name }}-eventbus
        image: {{ $deployment.image }}:{{ $deployment.imageTag }}
        args: ["event-bus"]
        ports:
        - containerPort: {{ $deployment.port }}
        #livenessProbe:
        #  httpGet:
        #    path: /_healthz
        #    port: {{ $deployment.port }}
        #  initialDelaySeconds: 5
        #  timeoutSeconds: 3
        #  failureThreshold: 2
        env:
          {{- range .Values.backend.env }}
          - name: {{ . }}
            valueFrom:
              secretKeyRef:
                name: {{ $deploymentName }}-env
                key: {{ . }}
          {{- end }}
